server:
  port: 1002

spring:
  redis:
    database: 0
    host: 106.14.218.153
    port: 6379
    timeout: 5000ms
    pool:
      timeout: 0
    password: shark007
  servlet:
    multipart:
      max-file-size:  500MB
      max-request-size: 500MB
  datasource:
    username: root
    url: jdbc:mysql://linkjb.com:3306/linkdisk?characterEncoding=UTF-8&useSSL=false&useUnicode=true
    password: Scq86906218
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  application:
    name: service-regist
  output:
    ansi:
      enabled: always #默认开启彩色日志
mybatis:
  type-aliases-package: com.linkjb.serviceregist.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
########## 通用Mapper ##########
mapper:
  identity: MYSQL
  mappers: tk.mybatis.mapper.common.BaseMapper
  #设置以后，会去判断 insert 和 update 中符串类型!=’’
  not-empty: true
  # 枚举按简单类型处理
  #枚举按简单类型处理，如果有枚举字段则需要加上该配置才会做映射
  enum-as-simple-type: true
########## 分页插件 ##########
pagehelper:
  helper-dialect: mysql
  params: count=countSql
  reasonable: false
  support-methods-arguments: true
logging:
  level:
    com.linkjb.dao : debug
  config: classpath:logback-linkdisk.xml
pool:
  corePoolSize: 10
  maxPoolSize: 200
  queueCapacity: 10
main:
  allow-bean-definition-overriding: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1000/eureka/
