server:
  port: 1088
eureka:
  client:
    serviceUrl:
      #注册服务
      defaultZone: http://localhost:1000/eureka/
spring:
  application:
    name: service-websocket
  datasource:
    username: root
    url: jdbc:mysql://linkjb.com:3306/linkdisk?characterEncoding=UTF-8&useSSL=false&useUnicode=true
    password: ????
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  output:
    ansi:
      enabled: always #日志默认开启颜色
  rabbitmq:
    host: www.linkjb.com
    username: xiongge
    password: ???
    port: 5672
    publisher-confirms: true #  消息发送到交换机确认机制,是否确认回调
    listener:
      direct:
        retry:
          #开启重试
          enabled: true
          #重试次数，默认为 3 次
          max-attempts: 5
debug: true