server:
  port: 8018
spring:
  #  profiles:
  #    active: do-not-up //配置此项将读 application-do-not-up.yml
  output:
    ansi:
      #开启彩色日志
      enabled: always
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: bunengshuoa
    url: jdbc:mysql://linkjb.com:3306/mediasubscriber?characterEncoding=utf8
    type: com.alibaba.druid.pool.DruidDataSource

  #    driver-class-name: oracle.jdbc.driver.OracleDriver
  ##    url: jdbc:oracle:thin:@10.10.2.202:1521:orcl
  ##    type: com.alibaba.druid.pool.DruidDataSource
  ##    username: rcp
  ##    password: rcp
  ##    data-username:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    publisher-confirms: true #  消息发送到交换机确认机制,是否确认回调

mybatis:
  type-aliases-package: com.linkjb.servicebase.pojo
  mapper-locations: classpath:mapper/*.xml

logging:
  file: LinkCloudDisk.log
  level:
    com.linkjb.servicebase : debug
eureka:
  client:
    serviceUrl:
      #注册服务
      defaultZone: http://localhost:1000/eureka/