server:
  port: 8018
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@10.10.2.202:1521:orcl
    type: com.alibaba.druid.pool.DruidDataSource
    username: rcp
    password: rcp
    data-username:
mybatis:
  mapper-locations: classpath:mapper/*.xml
