server:
  port: 8018
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/mediasubscriber?characterEncoding=utf8
    type: com.alibaba.druid.pool.DruidDataSource

  #    driver-class-name: oracle.jdbc.driver.OracleDriver
  ##    url: jdbc:oracle:thin:@10.10.2.202:1521:orcl
  ##    type: com.alibaba.druid.pool.DruidDataSource
  ##    username: rcp
  ##    password: rcp
  ##    data-username:

mybatis:
  type-aliases-package: com.linkjb.servicebase.pojo
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    com.linkjb.servicebase : debug