server:
  port: 8087

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1000/eureka/

spring:
#  profiles:
#    active: do-not-up //配置
  application:
    name: service-fileoperation
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: jdbc:mysql://local:3306/springCloud
    username: username
    password: password
debug: true
