server:
  port: 1000
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
spring:
  application:
    name: eurka-server
  rabbitmq:
    port: 5672
    publisher-confirms: true #  消息发送到交换机确认机制,是否确认回调
    listener:
      direct:
        retry:
          #开启重试
          enabled: true
          #重试次数，默认为 3 次
          max-attempts: 5

